logging:
  level:
    org:
      springframework:
        r2dbc: TRACE
spring:
  thymeleaf:
    encoding: UTF-8
  r2dbc:
    url: r2dbc:h2:file:///~/web_blog-h2-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALS;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
